In [1]:
import pandas as pd
import numpy as np

In [2]:
data = np.load("../../IMGVR/SkipGram_embedding_IMGVR_extra.npy")
df = pd.DataFrame(data)

print(df.shape)

(144192, 100)

In [9]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.007464,0.032135,0.023175,0.010819,0.044533,-0.029914,-0.008041,-0.035343,0.010872,-0.003333,...,0.015318,-0.039715,0.009906,-0.036043,0.017253,-0.036838,0.007592,0.012789,0.033898,-0.003553
1,-0.079939,-0.557393,-0.733584,-0.020018,-0.381353,-1.625690,0.259802,-0.640867,-0.020425,1.154452,...,1.056579,0.577265,0.238010,0.453385,1.090511,0.639125,0.503999,0.001410,-0.400398,-0.039186
2,-0.033577,0.020094,-0.028904,0.182547,0.354601,-0.344863,0.152129,-0.016344,0.021715,-0.040697,...,-0.358476,0.469110,0.191624,0.183962,0.072970,-0.072899,0.619897,0.161639,-0.431456,0.230093
3,-0.028377,0.294077,0.089067,0.058224,-0.251111,-0.380363,1.020436,0.283272,-0.256612,0.653677,...,0.357485,0.115721,0.514390,0.343275,-0.573516,0.397055,0.837814,-0.695733,0.048433,0.402149
4,1.125986,0.442871,0.356776,0.214696,0.249352,-0.200964,0.537971,-0.974916,0.259691,0.204189,...,-0.068852,-1.159367,-0.222604,0.132825,0.510037,0.019042,0.072568,0.549692,-0.292650,0.483562

In [7]:
nodes = pd.read_csv("../data/transform/imgvr_extra/IMGVR_extra_KGX_nodes.tsv", sep="\t")
print(nodes.shape)

(144192, 4)

In [8]:
nodes.head()

,id,name,category,provided_by
0,vOTU:sg_502237,sg_502237,kbase:otu,GOLD
1,NCBItaxon:bacteria;proteobacteria;gammaproteob...,bacteria;proteobacteria;gammaproteobacteria;ps...,biolink:OrganismTaxon,GOLD
2,Contig_length:4,4,biolink:QuantityValue,GOLD
3,Virus_topology:concatemer,concatemer,biolink:Attribute,GOLD
4,NCBItaxon:monodnaviria;loebvirae;hofneiviricot...,monodnaviria;loebvirae;hofneiviricota;faservir...,biolink:OrganismTaxon,GOLD

In [12]:
df = df.set_index(nodes['id'])

In [13]:
df.to_csv("../../IMGVR/SkipGram_embedding_IMGVR_extra_wlabels.tsv", sep="\t")

In [16]:
dfnp = df.to_numpy()
np.save("../../IMGVR/SkipGram_embedding_IMGVR_extra_wlabels.npy", dfnp)

AttributeError: 'DataFrame' object has no attribute 'to_numpy'